version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: hono-postgres
    environment:
      POSTGRES_DB: hono
      POSTGRES_USER: hono
      POSTGRES_PASSWORD: hono123
    ports:
      - "5432:5432"
    volumes:
      - hono-postgres:/var/lib/postgresql/data
    restart: unless-stopped
  
volumes:
  hono-postgres:
